 language: node_js
 node_js:
   - "8.11.1"
 os: osx
 env:
   - CXX=g++-4.8
 addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.8

 sudo: required

 services:
  - couchdb

 # command to install dependencies
 install:
 - npm install -g chai --save-dev
 - npm install -g mocha --save-dev
 - npm install -g nano --save-dev
 - npm install



 # command to run tests
 script:
   - node couchdb.js
   - mocha

