 language: node_js
 node_js:
   - "8.11.1"

 env:
   - CXX=g++-4.8
 addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.8

 sudo: required

 services:
   - docker

 # command to install dependencies
 install:
 - npm install -g chai
 - npm install -g mocha
 - npm install -g nano



 # command to run tests
 script:
   - mocha

